### ISSUE TITLE
Issues in macOS 10.15 Catalina

### ISSUE THREAD

**Issue by rex4539** [HelloZeroNet/ZeroNet-dist#1] opened 2019-10-19 11:35 UTC
Many issues on the new macOS client.

I'm on macOS 10.15 Catalina.

Icon keeps jumping in dock endlessly and the app never actually launches properly.

A zeronet daemon is spawned though but the only way to shut it down is to kill it from Terminal.

I also see the following error recorded:

```
RSA ECC SSL CAcert generation failed, CAcert or CAkey files not exist. (4516904556:error:0EFFF068:configuration file routines:CRYPTO_internal:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/conf/conf_def.c:563:line 57)
```

**Comment by HelloZeroNet** [comment] 2019-10-23 16:01
Thanks for reporting

I was able to install 10.15 to a vmware vm and reproduce the problems:
- [x] Missing TCL/TK files (fixed by adding a minimal tk)
- [x] OpenSSL cert generation failed: Looks like macOS no longer includes OpenSSL. Instead it has LibreSSL that is not fully compatible with current method. 

Possible fixes: 
 - [x] Make cert generation compatible with libressl
 - [ ] Include OpenSSL

(I will publish the new version when all the problems fixed)

**Comment by HelloZeroNet** [comment] 2019-10-25 14:18
I made a modification to make it compatible with libressl bundled with macos (https://github.com/HelloZeroNet/ZeroNet/commit/448bb3ce985fce463f295618378d31e9f795f146) and also fixed the bouncing icon problem by adding a minimal tcl/tk environment. https://github.com/HelloZeroNet/ZeroNet-dist/commit/d21cbb1e029fb6aeb457f9de86af699934947d9c

The updated version is avaliable from: https://github.com/HelloZeroNet/ZeroNet-dist/archive/mac/ZeroNet-dist-mac.zip

// Tested on macOS 10.15 Beta (19A471t)

**Closed as completed by HelloZeroNet** 2019-10-25 14:18 UTC
Labels: bug
